#define true 1
#define false 0

#define SHMKEY 300
#define MSQKEY 65
#define SEMKEY 70

#define GET_PROCESS SIGUSR1
#define PROCESS_FINISHED_SIGNAL SIGUSR2

#define CHANGE_ALGORITHM SIGRTMIN
#define QUANTUM_FINISHED SIGRTMIN+1
#define CHANGE_BLOCKING SIGRTMIN+2
#define INTERRUPT_SIGNAL SIGRTMIN+4

#define HPF_ALGORITHM 1
#define SRTN_ALGORITHM 2
#define RR_ALGORITHM 3